# Generated by Django 3.1.1 on 2020-09-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='n_guest',
            new_name='guests',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='price',
        ),
    ]
