# Generated by Django 3.1.1 on 2020-09-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0002_auto_20200923_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='nombre',
            new_name='name',
        ),
    ]
