# Generated by Django 3.1.1 on 2020-09-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0004_auto_20200923_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='reservation_id',
            new_name='code',
        ),
    ]
